#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate the schematic diagrams for Fundamental Analysis Module 2
("Reading between the lines").

Same discipline as scripts/make_diagrams.py: every number drawn here is READ
from _data/case_study_2.yml (which is itself generated by
scripts/build_case_study_2.py), so a diagram can never disagree with the post
beside it. Re-run after re-running the model builder.

    <venv>/bin/python scripts/make_fa2_diagrams.py

Output (checked in — the Pages build does not run this):
  assets/charts/fa2-purchase-price-allocation.svg   goodwill post
  assets/charts/fa2-honest-vs-dressed.svg           forensic post (optional use)
"""
import os
import sys

try:
    import yaml
except ImportError:
    sys.exit("needs pyyaml")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "assets", "charts")

BLUE       = "#184f95"
BLUE_LIGHT = "#cde2fb"
BLUE_PALE  = "#e8f1fc"
GREEN      = "#2e7d5b"
GREEN_PALE = "#9ec9b5"
RED        = "#b3403a"
RED_PALE   = "#e0b0ad"
INK        = "#0b0b0b"
MUTED      = "#52514e"
RULE       = "#d8d8d8"
FONT = "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif"


def esc(s):
    return str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def text(x, y, s, size=13, fill=INK, weight="normal", anchor="start"):
    return ('<text x="%.1f" y="%.1f" font-family="%s" font-size="%s" fill="%s" '
            'font-weight="%s" text-anchor="%s">%s</text>' % (x, y, FONT, size, fill, weight, anchor, esc(s)))


def box(x, y, w, h, fill, stroke=RULE, r=4):
    return '<rect x="%.1f" y="%.1f" width="%.1f" height="%.1f" rx="%d" fill="%s" stroke="%s" stroke-width="1"/>' % (
        x, y, w, h, r, fill, stroke)


def svg(w, h, title, desc, body):
    return ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %d %d" width="100%%" role="img" '
            'aria-labelledby="t d">\n<title id="t">%s</title>\n<desc id="d">%s</desc>\n'
            '<rect width="%d" height="%d" fill="#ffffff"/>\n%s\n</svg>\n'
            % (w, h, esc(title), esc(desc), w, h, "\n".join(body)))


def purchase_price_allocation(c2):
    """Left bar: the Rs 600 Lakh price. Right bar: what it bought, stacked, with
    goodwill as the unexplained remainder on top."""
    a = c2["acquisition"]
    W, H = 720, 420
    top, bot = 80, 380
    avail = bot - top
    price = a["price"]

    o = [text(W / 2, 30, "Purchase price allocation: where the Rs %d Lakh went" % price, 16, INK, "600", "middle"),
         text(W / 2, 50, "Desi Bites buys Chatpata Foods, %s (fictional) — Rs Lakh" % a["date"], 11, MUTED, "normal", "middle")]

    # left: single block, the price
    o.append(text(190, 72, "WHAT WAS PAID", 11, MUTED, "600", "middle"))
    o.append(box(70, top, 240, avail, BLUE_LIGHT))
    o.append(text(190, top + avail / 2 - 6, "Cash consideration", 13, INK, "normal", "middle"))
    o.append(text(190, top + avail / 2 + 14, "%d" % price, 15, INK, "600", "middle"))

    # right: stacked identifiable assets (bottom), payables shown as a notch, goodwill on top
    o.append(text(530, 72, "WHAT WAS BOUGHT", 11, MUTED, "600", "middle"))
    items = [("Goodwill (the unexplained premium)", a["goodwill"], RED_PALE),
             ("Brand (intangible, 10-yr life)", a["brand_intangible"], BLUE_PALE),
             ("Trade receivables", a["receivables"], BLUE_PALE),
             ("Inventory", a["inventory"], BLUE_PALE),
             ("Plant & equipment (fair value)", a["fixed_assets"], BLUE_PALE)]
    gross = sum(v for _, v, _ in items)          # 650 = price + payables taken over
    scale = avail / float(gross)
    y = top
    for label, val, colour in items:
        h = val * scale
        o.append(box(410, y, 240, h - 2, colour))
        cy = y + (h - 2) / 2 + 4
        if h > 26:
            o.append(text(420, cy, label, 11, INK))
            o.append(text(642, cy, "%d" % val, 12, INK, "600", "end"))
        else:
            o.append(text(660, cy, "%s  %d" % (label, val), 10, MUTED))
        y += h
    # payables: a bracket showing the 50 that nets off
    o.append(text(530, bot + 16, "less trade payables taken over: -%d  ->  identifiable net assets %d" % (
        a["payables"], a["identifiable_net_assets"]), 10.5, MUTED, "normal", "middle"))
    # goodwill callout
    gh = a["goodwill"] * scale
    o.append(text(660, top + gh / 2 - 2, "%.0f%% of the price" % a["goodwill_pct_of_price"], 11, RED, "600"))
    o.append(text(660, top + gh / 2 + 13, "not amortised; tested", 10, MUTED))
    o.append(text(660, top + gh / 2 + 26, "for impairment yearly", 10, MUTED))
    # equals sign
    o.append(text(360, top + avail / 2 + 6, "=", 26, MUTED, "600", "middle"))
    return svg(W, H, "Purchase price allocation",
               "Rs %d Lakh paid; identifiable net assets %d; goodwill %d (%.0f%% of the price)." % (
                   price, a["identifiable_net_assets"], a["goodwill"], a["goodwill_pct_of_price"]), o)


def honest_vs_dressed(c2):
    """Four ratio pairs, honest vs dressed, as paired horizontal bars."""
    h, d = c2["fy26"]["ratios"], c2["fy26_dressed"]["ratios"]
    rows = [("PAT (Rs Lakh)", c2["fy26"]["pat"], c2["fy26_dressed"]["pat"], 500),
            ("Operating cash flow (Rs Lakh)", c2["fy26"]["cash_flow"]["cfo"], c2["fy26_dressed"]["cash_flow"]["cfo"], 500),
            ("OCF / PAT (x)", h["ocf_pat"], d["ocf_pat"], 2.0),
            ("Debtor days", h["receivable_days"], d["receivable_days"], 60)]
    W, H = 720, 330
    o = [text(W / 2, 30, "Same business, two sets of books: FY26 honest vs dressed", 16, INK, "600", "middle"),
         text(W / 2, 50, "Desi Bites Foods (fictional). Profit moves; cash barely does.", 11, MUTED, "normal", "middle")]
    x0, bw, y = 250, 400, 78
    for label, hv, dv, mx in rows:
        o.append(text(240, y + 22, label, 12, INK, "normal", "end"))
        for i, (val, colour, tag) in enumerate(((hv, GREEN_PALE, "honest"), (dv, RED_PALE, "dressed"))):
            w = bw * float(val) / mx
            yy = y + i * 16
            o.append(box(x0, yy, w, 13, colour, colour, 2))
            o.append(text(x0 + w + 6, yy + 11, "%s %s" % (("%.2f" % val) if isinstance(val, float) and mx < 10 else "%d" % val, tag), 10.5, MUTED))
        y += 56
    return svg(W, H, "Honest vs dressed FY26",
               "PAT %d vs %d; operating cash flow %d vs %d; OCF/PAT %.2f vs %.2f; debtor days %d vs %d." % (
                   rows[0][1], rows[0][2], rows[1][1], rows[1][2], rows[2][1], rows[2][2], rows[3][1], rows[3][2]), o)


def main():
    c2 = yaml.safe_load(open(os.path.join(ROOT, "_data", "case_study_2.yml"), encoding="utf-8"))
    os.makedirs(OUT, exist_ok=True)
    for name, fn in (("fa2-purchase-price-allocation.svg", purchase_price_allocation),
                     ("fa2-honest-vs-dressed.svg", honest_vs_dressed)):
        path = os.path.join(OUT, name)
        with open(path, "w", encoding="utf-8") as f:
            f.write(fn(c2))
        print("wrote", os.path.relpath(path, ROOT))


if __name__ == "__main__":
    main()
